export const projects = [
  {
    title: "Gamesmith",
    description:
      "Gamesmith is a discovery platform that covers everyone working in the industry from accounting to animation, PR to product, development to deployment.",
    image: "/images/gamesmith.jpeg",
    tags: [
      "ReactJS",
      "NodeJS",
      "Sass",
      "Rest API",
      "Express",
      "AWS",
      "Firebase",
      "Docker",
    ],
    source: "https://github.com/Coders-Of-XDA-OT/covid19-status-android",
    visit: "https://gamesmith.com/",
    id: 0,
  },
  {
    title: "Otterwaiver",
    description: "Worry-Free Waiver Management.",
    image: "/images/otterwaiver.jpeg",
    tags: [
      "ReactJS",
      "TypeScript",
      "NodeJS",
      "Sass",
      "Rest API",
      "NestJS",
      "GraphQL",
      "PostgreSQL",
    ],
    source: "https://github.com/lordarcadius/website",
    visit: "https://otterwaiver.com/",
    id: 1,
  },
  {
    title: "Samuel-De Champlain Bridge",
    description:
      "Website for Montreal’s Samuel De Champlain Bridge one of North America’s busiest spans, with 50 million cars.",
    image: "/images/pontsamuel.jpeg",
    tags: ["WordPress", "PHP", "HTML", "CSS", "JavasScript", "JQuery"],
    source: "https://github.com/lordarcadius/ABS-Tweaks",
    visit: "https://www.samueldechamplainbridge.ca",
    id: 2,
  },
  {
    title: "Celani Wines",
    description: "Celani Family Vineyards and Wines website.",
    image: "/images/celani.jpeg",
    tags: ["HTML", "CSS3", "Sass", "Bulma Framework", "Gulp", "JavaScript"],
    source: "https://github.com/lordarcadius/electrablue_mido",
    visit: "https://celaniwines.com/",
    id: 3,
  },
  {
    title: "Circle",
    description: "The all-in-one community platform for creators & brands.",
    image: "/images/circle.jpeg",
    tags: ["Webflow", "HTML", "CSS", "JavaScript", "Figma"],
    source: "#",
    visit: "https://circle.so/",
    id: 4,
  },
  {
    title: "Choice Hotels",
    description: "Hotel and resort listings and reviews website.",
    image: "/images/hotels.jpeg",
    tags: ["ReactJS", "Sass", "Rest API", "Express"],
    source: "#",
    visit: "https://www.choicehotels.com/",
    id: 5,
  },
  {
    title: "Canadian Paint and Coatings Association",
    description:
      "Website for Montreal’s Samuel De Champlain Bridge one of North America’s busiest spans, with 50 million cars.",
    image: "/images/cpca.jpeg",
    tags: ["WordPress", "PHP", "HTML", "CSS", "JavasScript", "JQuery"],
    source: "https://github.com/lordarcadius/ABS-Tweaks",
    visit: "https://canpaint.com/",
    id: 6,
  },
];

export const TimeLineData = [
  { year: 2016, text: "Started my journey as a new developer." },
  { year: 2017, text: "Worked intensively on ROMs & Kernels." },
  { year: 2018, text: "Learned Android app development." },
  { year: 2019, text: "Finished Diploma in Computer Engineering." },
  { year: 2020, text: "Got a scholarship from the Delhi government." },
  { year: 2021, text: "Still trying to figure out this weird year." },
];
